---
- name: Copy bekind_linux to its new home
  hosts: prod
  tasks:
    - name: Create dest bekind dirs
      become: true
      file:
        path: "{{ item }}"
        mode: '0755'
        state: directory
        owner: bekind
        group: bekind
      loop:
        - /opt/bekind/web
        - /opt/bekind/logs
        - /opt/bekind/cache
        - /opt/bekind/cache/repo
      tags:
        - dirs

    - name: Copy bekind_linux to its new home
      become: true
      copy:
        src: ../cmd/bekind_linux
        dest: /opt/bekind/bekind
        owner: bekind
        group: bekind
        mode: '0755'
      tags:
        - binary

    - name: Enable the bekind service and start
      become: yes
      systemd:
        name: bekind
        enabled: yes
        state: restarted
      tags:
        - binary

    - name: clone tracks
      become: yes
      ansible.builtin.git:
        repo: https://github.com/shmul/zifim.git
        dest: /opt/bekind/cache/repo
        single_branch: yes
        version: master
        depth: 1
      tags:
        - git
