---
- name: Installation and Setup of bekind service
  hosts: prod
  tasks:

   - name: Creating a service file
     become: yes
     copy:
      dest: /etc/systemd/system/bekind.service
      content: |
        [Unit]
        Description=Bekind Service
        Requires=network.target
        After=network.target

        [Service]
        Type=simple
        User=bekind
        Group=bekind
        Environment="BEKIND_CONFIG_FILE=/opt/bekind/config.ini"
        WorkingDirectory=/opt/bekind/
        ExecStart=/opt/bekind/bekind web
        #ExecStop=/opt/tomcat8/bin/shutdown.sh
        Restart=always
        AmbientCapabilities=CAP_NET_BIND_SERVICE

        [Install]
        WantedBy=multi-user.target

   - name: Reload the SystemD to re-read configurations
     become: yes
     systemd:
        daemon-reload: yes

   - name: Enable the bekind service and start
     become: yes
     systemd:
        name: bekind
        enabled: yes
        state: started
